# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossproduct',
            options={'ordering': ('-created',)},
        ),
    ]
